apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - postgres.yaml
  - kafka.yaml
  - db-init.yaml
  - deployment.yaml
  - wal-consumer.yaml
  - data-pump-go.yaml
  - monitoring.yaml
  - loki.yaml
  - promtail.yaml
  - storage.yaml

labels:
  - pairs:
      app: wal-writer

configMapGenerator:
  - name: wal-writer-config
    literals:
      - WAL_WRITER_PG_HOST=postgres.cdc.svc.cluster.local
      - WAL_WRITER_PG_PORT=5432
      - WAL_WRITER_PG_USER=postgres
      - WAL_WRITER_PG_DATABASE=postgres
      - WAL_WRITER_PG_SLOT_NAME=wal_writer_slot_v2
      - WAL_WRITER_KAFKA_BROKERS=kafka.cdc.svc.cluster.local:9092
      - WAL_WRITER_KAFKA_TOPIC_PREFIX=cdc
      - WAL_WRITER_PUBLICATION=wal_writer_publication

images:
  - name: wal-writer-rust
    newTag: latest

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: wal-writer
      labelSelector: app=wal-writer

